[package]
name = "renarwhal"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.13"
ethers-core = "2.0.13"
hex-literal = "0.4.1"
tokio = { version = "1", features = ["full"] }

